### ISSUE TITLE
Regarding Fair/Unfair performance with UTK-Fairface

### ISSUE THREAD

**Issue by mohitsharma29** [umd-huang-lab/transfer-fairness#3]
Hey

Thank You for responding to previous issues very promptly. 
I am using the recommended settings to transfer fairness between UTK and Fairface. However, averaged across multiple runs, we observe that the unfair FairCons(fair_weight=0 and no --fair-cons) is better in terms of fairness than the fair version(--fair-cons True and fair_weight=1) for equalized odds metric. The model was trained to mitigate equalized odds but does not do well. But we get the expected results for Acc_Var. Here are the plots:

![download](https://github.com/umd-huang-lab/transfer-fairness/assets/15522704/5c12489b-b2ce-49e6-b091-a6b96d6b175e)
![download](https://github.com/umd-huang-lab/transfer-fairness/assets/15522704/2c1e5e22-5a60-4b71-b021-c4a143b947c3)

I believe the paper does not have this ablation. It only has a comparison to other fair transfer settings. Can you share your thoughts on this?

**Comment by bangann** [comment]
Thanks for the question. If I understand it correctly, what you did is Base+FixMatch which is indeed not included in our experiments. We didn't do it because we also wanted the model to be fair in the source domain. So all experiments are based on a fair algorithm (Laftr or CFair). Have you checked the fairness in the source domain? And we suggest looking at Pareto Frontiers since there's usually a trade-off between accuracy and fairness.

**Comment by mohitsharma29** [comment]
Thank you for the suggestions. I have not tried the other things you mentioned in your response. I think yours is a better way to compare since these are too complicated to be compared with a single number.
